#--- PaginaWeb
version: '3.7'
services:
  web:
    image: pavelzago/web:v3
    #build: .
    restart: always
    container_name: web
    hostname: web    
    ports:
      - "8000:8000"
    depends_on:
      - database
    # Mount volume 
    #networks:
     # - app
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_USER=testuser"
      - "MYSQL_PASSWORD=admin123"
      - "MYSQL_DATABASE=todobase"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.has-ssd == yes
    
    # Link database container to app container 
    # for reachability.
    
  database:

    # image to fetch from docker hub
    image: mysql/mysql-server:5.7
    restart: always
    container_name: database
    hostname: database
    ports:
      - "3309:3306"
    


    # Environment variables for startup script
    # container will use these variables
    # to start the container with these define variables. 
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_USER=testuser"
      - "MYSQL_PASSWORD=admin123"
      - "MYSQL_DATABASE=todobase"
    # Mount init.sql file to automatically run 
    # and create tables for us.
    # everything in docker-entrypoint-initdb.d folder
    # is executed as soon as container is up nd running.
#    volumes:
#     - "/usercode/db/init.sql:/docker-entrypoint-initdb.d/init.sql"
    #networks:
      #- app 
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.has-ssd == yes
  
#networks:
 # app:
  #  driver: overlay
